---
title: 'BYU Stat 223: Applied R Programming'
output: html_document
---

This is the homepage for BYU Stats 223: Applied R Programming.

---

**Section 5** | TTh 3:25 - 4:45 | *174 TNRB*


**Section 7** | TTh 4:55 - 6:15 | *174 TNRB*

---

### Instructor
The instructor for this course is James Blair.

* Office: 237 TMCB (On campus Tue and Thur only)
  * Office Hours:
    * Tuesday 1:30-2:30 pm
    * Thursday 12-1 pm
* Email: [blair@stat.byu.edu](mailto:blair@stat.byu.edu)

### TAs
* [Thomas Jensen](mailto:tompjensen@gmail.com)
  * Office Hours (235 TMCB):
    * Monday 2 - 3 pm
    * Wednesday 2 - 3 pm
    * Friday 2 - 3 pm
* [Brandon Allen](mailto:ballenor@comcast.net)
  * Office Hours (235 TMCB):
    * Monday 12 - 2 pm
    * Wedesday 12 - 2 pm
    * Additional time: Email [ballenor@comcast.net](mailto:ballenor@comcast.net) 
    to set up a time
* [Jacob West](mailto:jacobrobertwest@gmail.com)
  * Office Hours (235 TMCB):
    * Monday 10 - 11 am; 3 - 4 pm
    * Wednesday 10 - 11 am; 3 - 4 pm
    * Friday 10 - 11 am
* [Adam Ott](mailto:adderotter@hotmail.com)
  * Office Hours (235 TMCB):
    * Monday 4 - 6 pm
    * Thursday 10 - 11 am
    * Friday 1 - 2 pm