---
title: "Notes"
output: html_document
---

<!--
Possible R Moments:
- Reticulate
- blogdown
- plumber
- opencpu

-->

#### 2018-09-13

*Prayer is a supernal gift of our Father in Heaven to every soul. Think of it: the absolute Supreme Being, the most all-knowing, all-seeing, all-powerful personage, encourages you and me, as insignificant as we are, to converse with Him as our Father.*

\- Richard G. Scott ([GC April 2007](https://www.lds.org/general-conference/2007/04/using-the-supernal-gift-of-prayer?lang=eng))

+ Announcements:
  + *Do you have questions about graduate school? The Integrated program? When
  to apply? What steps you need to take to apply? If so, we would like to invite
  you to an info session to learn about graduate school and our Integrated program.
  The info session will be held on Thursday, October 4 at 11:00am in 1105 JKB.*
+ R Moment: [r2d3](https://rstudio.github.io/r2d3/)
+ git and GitHub - the final chapter
+ [Homework 1](hw1.html) in class walkthrough
+ [Homework 2](hw2.html) is assigned
+ [Confidence intervals](http://onlinestatbook.com/2/estimation/mean.html) to 
assess Monte Carlo (simulation) error
+ Additional simulation study examples:
  + [Demonstration of central limit theorem](l03_central_limit_theorem.nb.html)
  + [Reflipping coins when tails](l03_flipping_coins.nb.html)


#### 2018-09-11

*Obedience opens the door to the constant companionship of the Holy Ghost. And 
the spiritual gifts and abilities activated by the power of the Holy Ghost enable 
us to avoid deception—and to see, to feel, to know, to understand, and to remember 
things as they really are. You and I have been endowed with a greater capacity for 
obedience precisely for these reasons.*

\- David A. Bednar ([Ensign June 2010](https://www.lds.org/ensign/2010/06/things-as-they-really-are?lang=eng))

+ Announcements:
  + [rstudio::conf](https://www.rstudio.com/conference/)
    + January 15 - 18 in Austin, TX
    + Large academic discounts available (sign up with .edu email)
    + Seriously, this is the best conference ever
+ R Moment: [gganimate](https://github.com/thomasp85/gganimate)
+ A word about [RStudio Projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)
  + *RStudio projects make it straightforward to divide your work into multiple 
  contexts, each with their own working directory, workspace, history, and source 
  documents.*
+ Fixing git and GitHub
+ Getting started with [Homework 1](hw1.html)

#### 2018-09-06

*I testify that his intelligence is vastly superior in every field to the very 
brightest mortals in those fields and that his intellect in scope and truth far 
exceeds all human intellects. I thank him for encapsulating that exquisite mind 
in both perfect love and perfect humility. His brilliance is not the 
“catch-me-if-you-can” kind, but a pleading and patient, “Come, follow me.”*

\- Neal A. Maxwell ([GC April 1976](https://www.lds.org/general-conference/1976/04/jesus-of-nazareth-savior-and-king?lang=eng))

+ Announcements:
  + [Department Opening Social](images/os-flyer.jpg)
+ R Moment: [Shiny](http://shiny.rstudio.com/gallery/)
+ [Setup ssh keys for GitHub](http://happygitwithr.com/ssh-keys.html)
+ Stat 123 Q&A
+ A word about [RMarkdown](https://rmarkdown.rstudio.com/) and 
[Notebooks](https://rmarkdown.rstudio.com/r_notebooks)
+ Getting started with [Homework 1](hw1.html)
+ Introduction to simulation studies:
  + "Simulation study" and "Monte Carlo study" are synonymous.
  + Represent a real-world process programatically in order to evaluate statistical
  properties
  + Uses include:
    + Describing distributions (e.g., mean, variance, quantiles).
    + Evaluating point estimators.
    + Evaluating confidence intervals.
    + Investigating the properties and performance of testing hypothesis procedures.
    + Checking the finite-sample statistical properties of estimators and testing 
    procedures that have been motivated through asymptotics.
    + and many others...
  + Especially useful when theoretical derivations are unavailable, difficult, 
    or intractable.
+ [Flipping coins](l02_coins.nb.html)

#### 2018-09-04

+ Overview of the course.
+ Getting Started in STAT 223
  + [R](https://cran.r-project.org) and 
  [RStudio](https://www.rstudio.com/products/rstudio/download/preview/)
  + [Version control](http://happygitwithr.com/)
    + [git](https://git-scm.com)
    + [GitHub](https://github.com)
  + [Intro survey](https://goo.gl/forms/kNZILd3zeZO5UBWI2)
+ [STAT 223 coding standards](coding-standards.html)
+ [Review of functions in STAT 123](l01_functions.html)
+ [Homework 1](hw1.html) is assigned
(due 2018-09-11 at 8am)
