---
title: "Syllabus"
output: html_document
---

# Course Description

Advanced R programming skills, advanced data techniques, simulation studies.

Prerequisites: STAT 123.


# Learning Outcomes

+ Install R, R packages, and RStudio.
+ Advanced data management, manipulate, and transform data.
+ Solve complex problems using advanced R programming methodology.
+ Perform simulation studies, e.g. Central Limit Theorem, confidence intervals, power, etc.

# Computing Platform

The computing platform for STAT 223 is your own laptop computer, desktop
computer, or a University-owned computer.  If you do not have your own computer,
please see James who can discuss options with you.


# Git for Homework and Exams

You will collaborate with James, the TA's, and fellow students using
[Git](https://git-scm.com/).  Homework and exams will be managed through [GitHub
classroom](https://classroom.github.com/classrooms/42946451-byu-stat-223-fall-2018-term-1).  
Each student will have their own personal repository.  The setup on your computer 
will happen in the first lecture.  After the first lecture, please see the TAs 
or James during office hours if you need help.


# Homework

Homework will be distributed on the course webpage and is due as indicated in
the assignment.  **Your homeowrk must be submitted via GitHub**. This involves
committing local changes and pushing to your repository on GitHub. Homework is 
not submitted if you do not successfully push to your GitHub repository when due.
Late homework is only accepted at the discretion of James and, if accepted, is
subject to a 50% penalty. Depending on the nature of the homework, it may be 
graded on correctness or effort.  If homework is graded on effort, the following 
guide will be used:

+ 0:  Nothing submitted
+ 5:  Little effort is evident
+ 8:  Substantial effort is evident but it is not obvious that it is correct
+ 10: Substantial effort is evident and it appears to be correct


# In Class Exercises

Some class periods will include an in class exercise.  You are welcome to take
whatever notes you'd like to take in your notebook, then just write your final
answers on your paper.  You are responsible for bring your own blank paper for
each exercise.  You don't need to show work for credit.  The content of the
exercise will not be graded --- placing your name on a sheet of paper will get
you credit for the quiz -- but will be discussed in class.  It is not uncommon
for at least some in class exercises to form the foundation of exam questions.
Your lowest exercise score will be dropped to compensate for misses due to
illness and other unforeseen circumstances.


# Exams

There will be a take-home midterm exam on a date to be announced later.  The
final exam will also be take-home.  Exams are designed to assess a student's 
mastery of concepts, skills, and connections between lecture and homework.


# Grading

Item               | Weight
-------------------|------:
In-Class Exercises |     5%
Homework           |    20%
Midterm Exam       |    35%
Final Exam         |    40%

Class attendance, participation, citizenship, and improvement over the course
may be used in determining final grades in extreme situations.  All course
material is kept on file for one semester.  Any review or appeal must be made
within that time frame. 

# Teaching Assistants

# Office Hours
My office is 237 TMCB. I will hold office hours on Tuesdays from 1-2 pm and 
Thursdays from 12-1 pm.

# Honor Code

In keeping with the principles of the BYU Honor Code, students are expected to
be honest in all of their academic work. Academic honesty means, most
fundamentally, that any work you present as your own must in fact be your own 
work and not that of another. Violations of this principle may result in a
failing grade in the course and additional disciplinary action by the 
university. Students are also expected to adhere to the Dress and Grooming
Standards. Adherence demonstrates respect for yourself and others and ensures
an effective learning and working environment. It is the university's
expectation, and every instructor's expectation in class, that each student
will abide by all Honor Code standards. Please call the Honor Code Office at
1-801-422-2847 if you have questions about those standards.


# Sexual Misconduct

As required by Title IX of the Education Amendments of 1972, the university
prohibits sex discrimination against any participant in its education programs
or activities. Title IX also prohibits sexual harassment --- including sexual
violence --- committed by or against students, university employees, and 
visitors to campus. As outlined in university policy, sexual harassment, dating
violence, domestic violence, sexual assault, and stalking are considered forms
of "Sexual Misconduct" prohibited by the university.

University policy requires any university employee in a teaching, managerial,
or supervisory role to report incidents of sexual misconduct that come to their
attention through various forms including face-to-face conversation, a written
class assignment or paper, class discussion, email, text, or social media post.
If you encounter sexual misconduct, please contact the Title IX Coordinator at
t9coordinator&#64;byu.edu or 1-801-422-2130 or Ethics Point at
https://titleix.byu.edu/report or 1-888-238-1062 (24-hours). Additional
information about Title IX and resources available to you can be found at
http://titleix.byu.edu.


# Student Disability

Brigham Young University is committed to providing a working and learning
atmosphere that reasonably accommodates qualified persons with disabilities. If
you have any disability which may impair your ability to complete this course
successfully, please contact the University Accessibility Center (UAC), 2170
WSC or 1-801-422-2767. Reasonable academic accommodations are reviewed for all 
students who have qualified, documented disabilities. The UAC can also assess
students for learning, attention, and emotional concerns. Services are 
coordinated with the student and instructor by the UAC. If you need assistance
or if you feel you have been unlawfully discriminated against on the basis of
disability, you may seek resolution through established grievance policy and 
procedures by contacting the Equal Employment Office at 1-801-422-5895, D-285
ASB.